# Generated by Django 5.2.3 on 2025-06-27 01:13

import django.db.models.deletion
import django.utils.timezone
import groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group (must be unique)', max_length=100, unique=True, validators=[groups.models.validate_group_name])),
                ('description', models.TextField(help_text="Description of the group's purpose", max_length=500, validators=[groups.models.validate_group_description])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the group was last updated')),
                ('creator', models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', help_text="User's role in the group", max_length=10)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user joined this group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of this group', related_name='joined_groups', through='groups.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
