# Generated by Django 5.2.3 on 2025-06-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for the post', max_length=500, null=True),
        ),
    ]
