# Generated by Django 5.2.3 on 2025-06-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional uploaded image for the post', null=True, upload_to='post_images/'),
        ),
    ]
